baseURL = "/"
languageCode = "en-us"
title = "Primary Colors"
theme = "primary-colors"
disqusShortname = "jamescbain"
paginate = 12
pygmentsCodeFences = true
pygmentsStyle = "solarized-light"
summaryLength = 10
copyright = "© 2017 - 2020 James Bain - All rights reserved"

[permalinks]
    post = "/:year/:monthname/:slug/"

[[menu.main]]
    name = "HOME"
    url = "/"
    weight = 10
[[menu.main]]
    name = "BLOG"
    url = "/posts/"
    weight = 20
[[menu.main]]
    name = "ABOUT"
    url = "/about/"
    weight = 30
[[menu.main]]
    name = "CONTACT"
    url = "/contact/"
    weight = 40

[params]
    welcomeMessage = "Hi!"
    welcomeSecondary = "I'm James."
    welcomeDescription = "computational anthropologist | data viz"

    shortBio = "Hey there, I'm James! I'm a computational anthropologist whose interested in how computational methods can be used to research and better understand what underpins human behavior. More specifically, my research revolves global patterns of migration and understanding the rhetoric surrounding the topic of immigration. I also believe in making science and research accessable to the general public and spend quite a bit of my time designing and developing software to make science more digestable."

    disableMathJax = false
    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

[params.logo]
    url = "personal_logo_without_name.png"
    width = 75
    alt = "logo"

[params.footer]
    message = "Get in touch"
    footerImage = "dog.png"
    email = "jamescbain@gmail.com"
    city = "Calgary, AB"


[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    url = "https://github.com/jcbain/"   
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    url = "https://twitter.com/gymbrane/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    url = "https://www.linkedin.com/in/james-c-bain/"
[[params.social]]
    name = "Pinterest"
    icon = "fab fa-pinterest fa-2x"
    url = "https://www.pinterest.com/jchesterbain/"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram fa-2x"
    url = "https://www.instagram.com/jamescbain/"
