baseurl = "/"
languageCode = "en-us"
title = "James Chester Bain, PhD"
theme = "pink-plesiosaur-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
paginate = 1

[permalinks]
    post = "/:year/:monthname/:slug/"


[params]
    welcomeMessage = "I'm James"
    description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor magna eget est lorem ipsum dolor sit amet. Amet est placerat in egestas erat imperdiet sed. Feugiat pretium nibh ipsum consequat. Massa sapien faucibus et molestie ac feugiat sed lectus. Dolor sit amet consectetur adipiscing elit. Amet massa vitae tortor condimentum lacinia quis. Nisl pretium fusce id velit ut tortor pretium. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Eu non diam phasellus vestibulum. </br>Eu feugiat pretium nibh ipsum consequat nisl. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Aenean et tortor at risus viverra adipiscing at in tellus. Facilisi morbi tempus iaculis urna id volutpat lacus. Amet nisl suscipit adipiscing bibendum. Ultricies mi eget mauris pharetra et ultrices neque. Maecenas volutpat blandit aliquam etiam erat velit scelerisque in dictum. Sapien pellentesque habitant morbi tristique senectus et. Nec ullamcorper sit amet risus nullam eget felis eget. Accumsan in nisl nisi scelerisque. Tellus orci ac auctor augue mauris augue neque. Diam quis enim lobortis scelerisque fermentum dui. Mattis molestie a iaculis at erat pellentesque adipiscing commodo. Tincidunt dui ut ornare lectus sit amet est placerat in."

    blogMessage = "I also blog from time to time"
    blogDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor magna eget est lorem ipsum dolor sit amet. Amet est placerat in egestas erat imperdiet sed. Feugiat pretium nibh ipsum consequat. Massa sapien faucibus et molestie ac feugiat sed lectus. Dolor sit amet consectetur adipiscing elit. Amet massa vitae tortor condimentum lacinia quis. Nisl pretium fusce id velit ut tortor pretium. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Eu non diam phasellus vestibulum."
    
    copyrightPerson = "pink plesiosaur"
    copyrightURL = "https://github.com/jcbain/pink-plesiosaur-theme"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "/images/dog_favicon.png"
    
    # Custom CSS
    custom_css = []
    
    # Custom JS
    custom_js = []

[params.contact]
    message = "Have a question? Reach out"
    city = "Calgary, AB 🇨🇦"
    email = "jamescbain@gmail.com"
    url = "mailto:jamescbain@gmail.com"
 
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    url = "https://github.com/jcbain/"   
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    url = "https://twitter.com/gymbrane/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    url = "https://www.linkedin.com/in/james-c-bain/"
[[params.social]]
    name = "Pinterest"
    icon = "fab fa-pinterest fa-2x"
    url = "https://www.pinterest.com/jchesterbain/"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram fa-2x"
    url = "https://www.instagram.com/jamescbain/"
[[params.social]]
    name = "Blog"
    icon = "fas fa-blog fa-2x"
    url = "/post"



